### ISSUE TITLE
texrecon removes many parts of the input mesh

### ISSUE THREAD

**Issue by mojovski** [nmoehrle/mvs-texturing#12]
Today I received my first results using texrecon and the resulting mesh is much smaller than the original input.
This is the input:
![input](http://ibin.co/23wjZI7wZXXi)

and this is the output:
![outout](http://ibin.co/23wjkDdl9SFv)

Are there some points, which I need to consider which can help to improve the result?

**Comment by nmoehrle** [comment]
This still seems to be an issue with the cameras.
At the moment we have no hole filling algorithm, because of that and with the assumption of small triangles we remove all triangles/faces which have not been seen by a view since we cannot texture them properly. We determine if a triangle is visible in a view by shooting rays from its vertices towards the view and check if all rays reach the view/camera.

Could you please look at the ```texrecon``` output and tell me how many faces have not been seen by a view.

Another issue could be back face culling, could you please verify that the normals of your mesh are correct.

To verify your camera/view parameters further you could use the rephoto function in UMVE ([Scene inspect]/[Operations]/[+]Rephotographer) this renders your mesh with the camera parameters of the view - the perspective should look like the one within the photo.

**Comment by mojovski** [comment]
Thank you very much. The rephotographer tool is even more awesome. :+1:  :) the results I obtained look a bit different. So I will have a closer look on this.

**Comment by nmoehrle** [comment]
Did you receive the desired results now?

**Comment by mojovski** [comment]
Not yet. I will be able to resume the investigation end of next week.

**Comment by nmoehrle** [comment]
Hope that you got the desired results, since I have not heard from you I am going to close the issue.
