### ISSUE TITLE
Any useful optimize option?

### ISSUE THREAD

**Issue by ShiwenH** [nmoehrle/mvs-texturing#127]
Hi. I've success fully compile with vs2015 after fixing some syntax issue.
This is the result from my own data.
![image](https://user-images.githubusercontent.com/15124336/69039545-19bc6200-0a27-11ea-8956-4da86ca4bcda.png)
After any addtional option for me to fix these flaws?

Thanks.

**Comment by nmoehrle** [comment]
Sadly these issues are most likely due to an imperfect reconstruction.
The algorithm further assumes a static scene and can only cope with changes if the majority of views observed the same static scene.

I am uncertain whether you will be able to parameterize the algorithm in a different way to deal with those flaws.
