### ISSUE TITLE
a problem may caused by environment

### ISSUE THREAD

**Issue by julian-wang** [nmoehrle/mvs-texturing#13]
I met a problem when I try to make on my Mac.  How can I solve this problem?
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [apps/texrecon/texrecon] Error 1
make[1]: *** [apps/texrecon/CMakeFiles/texrecon.dir/all] Error 2
make: *** [all] Error 2

By the way, where can I find the test data (sample images)  in this project?
Thanks a lot.

**Comment by nmoehrle** [comment]
I have never compiled anything on Mac before, but I have been able to reproduce the problem on a Mac of department. It appears that the issue is the version of the standard library which is shipped in xcode.
I have not been able to fix the issue and will consult some colleges, however this will take some time :-(

**Comment by nmoehrle** [comment]
The problem in my case and probably also your problem is, that the dependency mve is using make rather than cmake as build system, which is selecting a different stdlib. While I work out a way to fix this properly, these steps should get you going:
 1. run the normal build process which downloads and compiles mve
 2. switch to the source folder of mve (*mvs-texturing/elibs/mve/*)
 4. append `-stdlib=libc++` to line four of *Makefile.inc*
* (`sed -i.backup '4 s/$/ -stdlib=libc++/' Makefile.inc`)
 3. run `make clean && make`
 5. switch to your build folder
 6. run `make clean && make`

**Comment by nmoehrle** [comment]
I have talked to the developers of mve regarding their linking to `libstdc++`,  with the merge of their most recent pull request (https://github.com/simonfuhrmann/mve/pull/152) mve is now linking to libc++ on my Mac and mvs-texturing is compiling out of the box.

**Comment by julian-wang** [comment]
Thanks a lot for your solution.
However it generated a point cloud file without any point data When I did according to Quick Guide: mve/apps/scene2pset/scene2pset -F3 scene point-set.ply
I am not sure whether should I generate a bundle.nvm file and makescene using bundle.nvm file.

**Comment by nmoehrle** [comment]
To write out a scale three point set you have to run the multi view stereo algorithm on that scale, did you execute `dmrecon` with the reconstruction scale set to three? However, this is an issue with reconstruction steps prior to texturing which are covered by [mve](https://github.com/simonfuhrmann/mve) and [fssr](https://github.com/simonfuhrmann/fssr). Please state your issue in the according repository.
