### ISSUE TITLE
possible calibration (.cam) file importing on umve

### ISSUE THREAD

**Issue by ankarako** [nmoehrle/mvs-texturing#140]
Hi,

Is there a way to import the camera calibration parameters (intrinsics-extrinsics) along with their corresponding images in the umve application, just to check that the .cam files are correct or identify the different axis assumptions etc.?

Thanks in advance,
Antonis

**Comment by nmoehrle** [comment]
There is no script available at the moment but it is straight forward to convert cam files into .mve files since they both follow the convention by Hartley and Zisserman (cam files are actually a stripped-down version of the camera part of the old view file format). You can find the description for the MVE view file format here https://github.com/simonfuhrmann/mve/wiki/MVE-File-Format.
I highly encourage you to use an MVE scene as input to mvs-texturing for exactly the reason that you mentioned.

**Comment by ankarako** [comment]
Thank you very much for your answer, I will check it out ;)

**Comment by ankarako** [comment]
Hi again,
I successfully created the .mve view files, but it seems that the translation is not taken into account while rendering the frustra? Even if I use arbitrary high values for camera translation the corresponding frustrum is always rendered at the origin.  This does not happen with rotation though.

Thanks again

**Comment by nmoehrle** [comment]
Please verify the spelling, I think it will not complain if something is off there.
The translation is taken into account like this https://github.com/simonfuhrmann/mve/wiki/Math-Cookbook.

**Comment by ankarako** [comment]
Could you check this screen recording I made?
https://i.imgur.com/eFfLu1v.gifv

I think that even if I'm using wrong values for translation, I should see some frustrum movement there.

Thanks

**Comment by nmoehrle** [comment]
My assumption is that your file does not end with a newline character and that there is an issue with the parsing in MVE. Please add an empty line to the end of your file and try again.

**Comment by ankarako** [comment]
Thank you very much @nmoehrle :)
That did it.
Always grateful.
