### ISSUE TITLE
Color mapping

### ISSUE THREAD

**Issue by rhiestan** [nmoehrle/mvs-texturing#24]
In newer versions of texrecon, the color mapping is worse than before. As an example, I made a textured 3d reconstruction of the kermit scene (from bundler) with an old texrecon (github of around April 2015) and the current one (github of 23.09.2015). I have seen the same behaviour also with other scenes, however less drastic.
Is there a way to have the new features (MVS2 compatibility, reduced memory consumption) and the old color mapping?

Old texrecon:
![kermit_oldtexrecon](https://cloud.githubusercontent.com/assets/10052044/10076635/c629d74e-62dc-11e5-99e7-3d2a147e98e2.jpg)

New texrecon:
![kermit_newtexrecon](https://cloud.githubusercontent.com/assets/10052044/10076639/c98ecf48-62dc-11e5-8c20-36546f77abb6.jpg)

Both reconstructions were made with Regard3D (www.regard3d.org, I am the author).

Thanks in advance!

**Comment by nmoehrle** [comment]
A lot has changed since April especially regarding the handling of the input images. I am aware that the current linerar/gamma tonemapping of the HDR texture is not really robust and sometimes leads to bright textures with low contrast. I am currently thinking about how to tackle this issue btw. thanks for opening it on github :-) It's way easier to justify working on it now ;-)

Currently I use a linear mapping between the 0.005th and the 0.995th percentile [min-max](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_atlases.cpp#L109).
On difficult datasets this appears to be to optimistic, so I will have to clamp more rigorously.
I am reluctant to expose these parameters, but I might have to because they seem to be quite dataset dependent.
I will look into tonemapping and contrast enhancement, however, I am not sure when I will find the time.

**Comment by donlk** [comment]
Have you considered switching to mosaic based texture generation instead of atlases? That way pixel blending would be much more subtle and even throughout the entire mesh. Its what Agisoft Photoscan uses as well i assume, though It might be computationally expensive..

**Comment by nmoehrle** [comment]
To address the issue I have created a new branch "tone-mapping" and implemented the tone mapping algorithm of [Reinhard et al. [2002]](http://www.cmap.polytechnique.fr/~peyre/cours/x2005signal/hdr_photographic.pdf). I can see an enhancement of contrast on my datasets, can you confirm the effect?

**Comment by donlk** [comment]
Texture blending is alot better now! Although the histogram is way off:

NEW tone mapping [only local seam levelling]
![new_local_seam](https://cloud.githubusercontent.com/assets/651060/13129565/015b0832-d5de-11e5-9cb7-ac09c5067abf.png)
NEW tone mapping [local and global seam levelling]
![new_local_global_seam](https://cloud.githubusercontent.com/assets/651060/13129569/0ad55df4-d5de-11e5-997b-dccbcc811232.png)

OLD tone mapping [only local seam levelling]
![old_local_seam](https://cloud.githubusercontent.com/assets/651060/13129535/e2c41620-d5dd-11e5-8b66-2714500fd536.png)
OLD tone mapping [local and global seam levelling]
![old_local_global_seam](https://cloud.githubusercontent.com/assets/651060/13129541/e8860582-d5dd-11e5-8203-e588f5bf3f59.png)

**Comment by rhiestan** [comment]
Sorry for the late answer.
I see similar results like donlk. The color mapping is improved, but not yet on the same level as before.
With some data sets, I see better results, however the kermit dataset has still issues:
With only local seam leveling:
![kermit_newtexrecon2](https://cloud.githubusercontent.com/assets/10052044/13169904/cff9450e-d6e8-11e5-98d0-fca6e28bb4eb.jpg)
With global and local seam leveling:
![kermit_newtexrecon1](https://cloud.githubusercontent.com/assets/10052044/13169905/cffae8be-d6e8-11e5-901d-8cb162c46db4.jpg)


Thanks for the update!

**Comment by nmoehrle** [comment]
@rhiestan could you provide me the kermit dataset, it looks like a prime example for failure ;-)
Especially the red artifact on the right looks terrible and the histogram is looks weird too.

@donlk nice capture target :-) As far as I can tell the issue with the global seam leveling starts at the handle. The geometry is overestimated and therefore parts of the white background are used to texture it (because of the edges high gradient) which results in the leveling of pixels with different colors. I am not sure how to handle this since it is essentially an issue of geometry reconstruction. However, the outlier removal method might help with this since it will discard the views observing white.
I thought about down weighting gradients at depth discontinuities to cope with these artifacts, as far as I know this was first used by  [Callieri et al. [2008]](http://vcg.isti.cnr.it/Publications/2008/CCCS08/CG_textailor.pdf).

**Comment by rhiestan** [comment]
This is the kermit reconstruction, done with Regard3D:
[triangulation_0.zip](https://github.com/nmoehrle/mvs-texturing/files/137967/triangulation_0.zip)

If the current directory is triangulation_0, then my command line looks like this:
texrecon.exe --no_intermediate_results out\MVE2_SCENE_DIR::undistorted densification_0\surface_0\model_surface_trim.ply densification_0\surface_0/model_surface_text

If you would like the original pictures, they are here:
[kermit.zip](https://github.com/nmoehrle/mvs-texturing/files/137972/kermit.zip)
They are distributed with bundler by Noah Snavely, see here:
http://www.cs.cornell.edu/~snavely/bundler/

**Comment by rhiestan** [comment]
Thanks for the update, the results are much better. I still have local intensity differences, see attached pictures. But they are much smaller now.

![kermit_newtexrecon3](https://cloud.githubusercontent.com/assets/10052044/13525789/cb43e8b8-e203-11e5-9a3f-84ec95426d7c.jpg)
![sceaux_newtexrecon](https://cloud.githubusercontent.com/assets/10052044/13525793/cee1a032-e203-11e5-9b2d-2c224a267acc.jpg)

**Comment by nmoehrle** [comment]
Which outlier removal method are you using?

**Comment by rhiestan** [comment]
For the kermit model I did not use any outlier removal, for the sceaux castle (see https://github.com/openMVG/ImageDataset_SceauxCastle) I used "Gauss damping". But it did not make a big difference when other settings (none, Gauss clamping) were active. The Sceaux dataset is quite special with a tree partially obstructing the view in two pictures.

**Comment by xueao** [comment]
Thank you for your sharing!
Could you provide example of how scene::undistorted looking like to me. I have tried with BUNDLE_FILE in NVM format, SCENE_FOLDER and MVE_SCENE in the same folder, but it did not work.
Thank you!

**Comment by xueao** [comment]
Hi Nils
When I test texrecon program with color mesh generated by mve, the result seems bad as following : 
![snapshot100](https://cloud.githubusercontent.com/assets/11704620/17319648/a35ae510-58c1-11e6-9c55-112285aafd42.png)
The above result is achieved by setting a linear mapping  0.995th percentile min-max. If I turn down this parameter  percentile = hist_qualities.get_approx_percentile(0.455f),  the result gets a little better, but not good enough.While the colored mesh look like as follows:
![snapshot400](https://cloud.githubusercontent.com/assets/11704620/17319999/d769577c-58c3-11e6-9a23-c9cccee0d6a6.png)
So how should I adjust parameters to make it done well.
Thank you in advance.
Regards,
Xueao

**Comment by nmoehrle** [comment]
It appears to me that there are a lot of occluders within the scene (and the texture). Did you use a outlier removal method (e.g. `--outlier_removal=gauss_clamping`)?

**Comment by xueao** [comment]
@nmoehrle 
It works!
Thank you!
