### ISSUE TITLE
Issues trying to compile with MSVC in regards to OpenMP and C99 support

### ISSUE THREAD

**Issue by Smozeley** [nmoehrle/mvs-texturing#26]
Hello,

I am trying but failing to compile your code using vs2013 community but I have also tried 2015 community and 2012 professional. the issues seem to boil down to OpenMP 3.0 and C99 support. Apparently none of the Microsoft compilers support OpenMP 3.0 nor do they plan too which seems short sited to me. they only support 2.0 and I am getting several errors regarding 3.0 usage.  For example:

Error	14	error C3048: Expression following '#pragma omp atomic' has improper form	..\libs\tex\progress_counter.h	51	1	tex

Also, although they have implemented some C99 support its not all there. for example

Error	54	error C3016: 'i' : index variable in OpenMP 'for' statement must have signed integral type	..\libs\tex\

I am able to get most projects to compile except mrf, tex and texrecon. Maybe I am total off base so I would welcome any advice otherwise I will keep trying to get around these issues and get everything to compile with MSVC :)

Best Regards,
Scott Mozeley

**Comment by nmoehrle** [comment]
Hi Scott,

one of my colleagues Andre is working under Windows and maintains a MSVC compatible [fork](https://github.com/andre-schulz/mvs-texturing). The plan was that necessary changes will be merged back into this repository. However, since the development of mvs-texturing is ongoing and testing MVSC compatibility is difficult for me, we decided to keep them separate for the moment.

Using Andres fork would probably be the best choice for you. However, his fork is currently three commits behind and those are important, because of an issue with ```std::tmpnam``` under Windows. The issue has been fixed but not pushed yet, I will ask him to do it as soon as possible.
You can also use his fork and cherry-pick e4a4f2b which resolves the issue; that should work straight away.

Best wishes,
Nils

**Comment by Smozeley** [comment]
Ok Nils thank you. I will take a look at Andres fork.
