### ISSUE TITLE
Running the texturing code with .cam files

### ISSUE THREAD

**Issue by ssundar6087** [nmoehrle/mvs-texturing#29]
Hi,

I'm trying to run the code in linux using my own data. I have the images, the .cam files and the mesh in "image_dir" and used the following call : 

~/mvs-texturing/build/apps/texrecon/texrecon image_dir input.ply textured

The code crashes with a segmentation fault. Is there something that I'm doing wrong?

Thanks

**Comment by nmoehrle** [comment]
If there is an segmentation fault it's always the developers fault - in that case mine ;-)

To investigate your issue could you please recompile the code in debug configuration (```cmake .. -DCMAKE_BUILD_TYPE=DEBUG```), run it again and then post the output here.

It's way after midnight on my side of the planet so I probably won't able to respond right away, please excuse ;-) I'll do it first thing in the morning. 

Best wishes,
Nils 

PS. Please use markdown for the output

**Comment by ssundar6087** [comment]
Hi Nils,

Here is the output I got upon recompiling with the Debug flag and re-running the code : 
```
Received signal SIGSEGV (segmentation fault)
Obtained 7 stack frames: 0x4bead1 0x7fc09d44dd40 0x460bc8 0x46168a 0x42880f 0x7fc09d438ec5 0x42a533
/home/sairams/mvs-texturing/build/apps/texrecon/texrecon(_ZN4util6system17print_stack_traceEv+0x21)[0x4bead1]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7fc09d44dd40]
/home/sairams/mvs-texturing/build/apps/texrecon/texrecon[0x460bc8]
/home/sairams/mvs-texturing/build/apps/texrecon/texrecon(_ZN3tex20global_seam_levelingERK8UniGraphSt10shared_ptrIKN3mve12TriangleMeshEERKNS4_8MeshInfoERKSt6vectorISB_INS_20VertexProjectionInfoESaISC_EESaISE_EEPSB_IS3_I12TexturePatchESaISK_EE+0xa5a)[0x46168a]
/home/sairams/mvs-texturing/build/apps/texrecon/texrecon(main+0x97f)[0x42880f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fc09d438ec5]
/home/sairams/mvs-texturing/build/apps/texrecon/texrecon[0x42a533]
Segmentation fault
```
Let me know if you need further info. 

Thanks!

**Comment by nmoehrle** [comment]
OK there is definitely an issue with the cam files,  because none of the faces is visible in any view. Nevertheless there shouldn't have been a segfault I'll fix that...

To your cam files: I would highly advice you to convert your scene into the mve scene format. It would enable you to inspect the cameras visually using UMVE. 

Debugging cam files is really tricky but here are some hints:
- make sure you specified a camera translation vector rather than a camera position
- the focal length should be divided by the larger image dimension and is usually between 0.5 and 2
- make sure to provide first the translation vector and than the coefficients of the rotation matrix
- provide the rotation matrix in column major order

If you run texrecon without any arguments it will print the cam file specification.

Hope this helps, if not could you upload a zip file with some cam files and corresponding images so that I can have a look at it?

Best wishes, 
Nils

**Comment by ssundar6087** [comment]
I'm not sure how to attach the zip file here, Nils. I tried to do that and it didn't work. Is there another way I can get the files to you?

**Comment by nmoehrle** [comment]
The .cam files have to be named like the image files - only the extension should be different.

Can you upload it onto a service like Google Drive or Dropbox and just share the link here or mail it to me (if you do not want the data to be publicly available).
