### ISSUE TITLE
texrecon crashes

### ISSUE THREAD

**Issue by pglira** [nmoehrle/mvs-texturing#34]
Thanks for sharing your code!

The last version of texrecon (compiled yesterday) crashes for the following dataset:
https://www.dropbox.com/s/fvh6wbzgq9zs9ms/texrecon_test_now_complete.zip?dl=0
(Update: one image was missing in the first version of the zip archive. Now it's complete.)

The command I used is:
![2016_02_02_08_40_28](https://cloud.githubusercontent.com/assets/14214284/12742745/c4b6f3c0-c988-11e5-95b2-ef3b944fc5df.png)

Do you have any idea what may be the problem?

Regards,
Philipp

**Comment by nmoehrle** [comment]
There is an issue with the nvm importer under Windows, although it works under Linux it should be removed entirely. As a workaround you can create a MVE scene and use it for texturing.

Since you have been able to build texrecon under Windows I assume you managed to compile mve and the mve apps as well. To create an mve scene from the nvm file simply run ```makescene.exe VSFMResult.nvm scene``` (makescene is located in ```mvs-texturing\elibs\mve\apps\makescene```). Afterwards you can texture your mesh with ```texrecon.exe scene::undistorted mesh.ply mesh_texturized```.

I am sorry for the inconvenience. When I merged the lowmem branch a few months back I forgot that the support for SCENE_FOLDERS and BUNDLE_FILES was rather rudimentary and not portable. For this and other issues I will have to remove support for these scene representations, however, I will provide an app to convert old datasets.

Best wishes,
Nils

**Comment by pglira** [comment]
Thanks for your reply. My colleague managed to change the code in a way that texrecon doesn't crash anymore.

**Comment by WKarel** [comment]
I'm pglira's colleague who compiled texrecon on Windows 7 x64 using Visual Studio 2015. Having altered the optimization settings for libpng, texrecon now runs fine.
Unfortunately, VS 2015 still only supports OpenMP 2.0 and thus, changes in the code were needed, mostly:

1. change OpenMP loop variable types (size_t -> int64_t),
2. replace the OpenMP-task with a thread-pool (using boost.threads), and
3. create directories ("tmp", output) before texrecon tries to save files into them.

I have not encountered any problems with the nvm import specifically, and thus I see **no** requirement to remove it on Windows!

**Comment by nmoehrle** [comment]
I was thinking about removing the nvm importer because saving temporary files is a questionable design decision. On that note, which path have you chosen for those temporary files?

**Comment by WKarel** [comment]
The path is "tmp", relative to the current working directory.

**Comment by hushanming** [comment]
Hi,@WKarel,@nmoehrle
I have encountered the same problem when I used the command: 
_D:\vs2013\mvs-texturing-master\mvs-texturing-master\build\apps\texrecon\Release\texrecon.exe bundle.nvm surface-clean.ply tex1_
The data I used is the [der_hass-20140923](http://www.gcc.tu-darmstadt.de/home/proj/mve/) on the offical website.
and I found the  problem lies this  [line](https://github.com/nmoehrle/mve/blob/master/libs/mve/image_io.cc#L63).So I guess there something wrong in the libpng library.Do you have any idea what may be the problem? How do you optimize the libpng library?

**Comment by andre-schulz** [comment]
Hi @hushanming,
can you please try the following patch and see if it fixes the problem for you?
https://github.com/andre-schulz/mvs-texturing/commit/d23e52980533992fca5a704058fb8c7ef8cc982b
Thanks in advance.

**Comment by hushanming** [comment]
Hi,andre-schulz
I am sorry to reply very late, I tried the method you provided, but still can not solve the problem,I guess  there is something wrong with loading images because it shows
_D:\vs2013\mvs-texturing-master\mvs-texturing-master\build\apps\texrecon\Release\texrecon.exe (built on Oct  2 2016, 09:27:29)
Load and prepare mesh:
PLY Loader: comment Export generated by libmve
Reading PLY: 121043 verts... 238279 faces... done.
Generating texture views:
NVM: Loading file...
NVM: Number of views: 79
NVM: Number of features: 61172
./IMG_0189.JPG
./IMG_0140.JPG
./IMG_0209.JPG
./I请按任意键继续. . ._
Thank you very much for your answer, I will continue to work hard.

**Comment by nmoehrle** [comment]
Andre is working on a solution, there is still n issue with the 'tmp' directory on windows.

I would advise to use MVEs [makescene](https://github.com/nmoehrle/mve/blob/master/apps/makescene/makescene.cc#L880) to generate a MVE scene from the nvm file as the support for nvm files is in a bad shape - sorry...

**Comment by toke500** [comment]
Hello @WKarel 

Would you mind sharing which libpng settings you have changed?

Thanks in advance

Regards,
Toke

**Comment by WKarel** [comment]
Hi Toke,

I deactivated (fast) link-time code generation for release-builds.

Cheers,
Willi.

**Comment by toke500** [comment]
Hello Willi

Thank you for the quick reply. It doesnt seem to be the problem in my case.

Regards,
Toke

**Comment by d41k4n** [comment]
@WKarel, @pglira and all,

Would it be possible to share the windows binaries (again)? The dropbox links are all dead and I'd be certainly very grateful!

Thanks.
