### ISSUE TITLE
problem of using the -D -L options

### ISSUE THREAD

**Issue by xialang2012** [nmoehrle/mvs-texturing#47]
I used the 
`./texrecon nvmCams.nvm odm_mesh.ply tex`
to get a texture material result which showed below

![tex_material0000_map_kd](https://cloud.githubusercontent.com/assets/14291651/16290230/3fccc5de-392e-11e6-88c0-31968c7b9570.png)

Then, I used the 
`./texrecon nvmCams.nvm odm_mesh.ply tex-D -D tex_data_costs.spt -L tex_labeling.vec`
to skip calculate the costs and labels, but the result is strange
![tex-d_material0000_map_kd](https://cloud.githubusercontent.com/assets/14291651/16290274/88204a4a-392e-11e6-80fd-5be6e110013e.png)

I think they shouled be the same, but it seems not.

**Comment by nmoehrle** [comment]
You are right the result should be the same, even more so since `-L` "overrides" `-D`.
I usually use pink as debug color, so it should not appear in any final texture atlas...
Nvm is seldomly used by our group and therefore the support has not been tested as thorough. I will look into the issue, but I might not have time to do so this week.
