### ISSUE TITLE
UVs

### ISSUE THREAD

**Issue by fabiencastan** [nmoehrle/mvs-texturing#5]
Is it possible to keep the UVs of my 3D model?
If not, is it planned?
If not, do you have some inputs on how to do it?

**Comment by nmoehrle** [comment]
Hi Fabien,

I didn't completely grasp your intention, could you please describe your scenario.

However, maybe I can clarify it right away: our algorithm constructs a texture from unwarped images and to do so assigns new texture coordinates and creates texture atlases. It is not designed to texture artificial meshes with hand created UV mappings.
Maybe you are searching for something like [flexi stickers][1].

[1]: http://www.cs.technion.ac.il/~ytzur/flexiStickers/flexi.html]

**Comment by nmoehrle** [comment]
Closed due to inactivity.

**Comment by fabiencastan** [comment]
Hi Nils,

I was busy and I missed your answer.
The use case is simple, we create a reconstruction with MVE and MVS-texturing. Then we clean the mesh manually and we create a mesh at multiple resolutions. The problem is that the auto-UVs provided by MVS-texturing contains a lot of texture seams which produce visible artifacts.
So we create custom UVs to resolve that, but we have no way to re-run MVS-texturing with those user UVs.

I dont know if it's complicated to add an option in MVE-texturing to avoid the UV generation to directly use user UVs.

Regards,
Fabien

**Comment by nmoehrle** [comment]
Hi Fabien,

to use manually defined UV mappings within our application would be a mayor change since our method avoids warping of images completely and therefore has to create texture coordinates accordingly. I wont have time to implement such a feature in the future. However, it should be fairly simple to "transfer" the the texture from our textured reconstruction to a reconstruction with manual texture coordinates: 
Since our algorithm basically guarantees that texels on a seam have the same color in each triangle you should be able to iterate over each face in your mesh and simply do a lookup for each texel in our textured reconstruction. However, since the scales will be different keep in mind to lookup in an appropriate scale - by scaling the texture atlases. To avoid border artifacts during re-scaling you can disable the filling of invalid pixels (build_obj_model.cpp) and mask them during scaling.
If you provide me with a textured reconstruction and a mesh with UV coordinates I will try to find the time to implement such an post processing application.

Regards,
Nils

**Comment by fabiencastan** [comment]
Thanks a lot! That would be amazing.
I will create a dataset that can be shared publicly in the beginning of the next week.

**Comment by fabiencastan** [comment]
You can find all the data here:
https://drive.google.com/file/d/0B7jDgO5LuWmdVTZGdTB2Uno5b3M/view?usp=sharing

The inputs are:
- all the input images
- the input "mve" directory
- the input mesh in PLY format

Then you have the OBJ generated using texrecon with automatic texturing and automatic UVs (I also provided all the input data to regenerate it, if you need).
And finally you have the same OBJ with user defined UVs, where we would like to retrieve the texturing.

Thanks again!

**Comment by nmoehrle** [comment]
HI Fabien,
I had a quick look at the dataset. Sadly I saw that during the manual uv creation the face face correspondence got lost (the faces with id X are not the same in each of the models) and I assume the same goes for vertices. I would still be possible to transfer the texture but it is not a simple lookup, I would have to determine corresponding texels either through a nearest neighbor lookup of the texels face vertices between the meshes or through ray casting/collision detection.
It will take a while before I will have time to do that. I'll let you now when I have news.

**Comment by xueao** [comment]
@nmoehrle 
Hi nmoehrle,
I tried your mvs-texturing program and it worked well. However, I'm wonder if there was a way to reduce the number of texture maps. When I built a scene with 200 images, I would get lots of texture maps. Like this:
![qq 20160506191339](https://cloud.githubusercontent.com/assets/11704620/15071786/ec59d96a-13c0-11e6-8f51-0f209c873db1.png)
I don't know if there was  a way to fuse these texture maps into one.
Thank you!

**Comment by xueao** [comment]
@nmoehrle 
Hi nmoehrle,
I tried your mvs-texturing program and it worked well. However, I'm wonder if there was a way to reduce the number of texture maps. When I built a scene with 200 images, I would get lots of texture maps. Like this:
![qq 20160506193348](https://cloud.githubusercontent.com/assets/11704620/15071907/bb02625a-13c1-11e6-9b7c-590a18af436c.png)
I don't know if there was a way to fuse these texture maps into one.
Thank you!

**Comment by nmoehrle** [comment]
Hi Xueao,

goal of this project is to create the best texture w.r.t. visual quality, which has implications on the handling of images (e.g. no scaling or distorting of the original images). As you experienced this can also lead to a lot of texture patches. The number of texture atlases is controlled by a [heuristic](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_atlases.cpp#L35) which tries to minimize the wasted space due to edge padding.

I always wanted to add another post processing step to make the resulting model more appropriate for interactive use cases such as games. While I had no time to write it from scratch, I was recently involved in the http://www.instantuv.org/ project which is a library specifically designed for this kind of post processing and might be what you are searching for.

If you want to tweak the texturing code itself you may alter the heuristic or increase the [PREF_TEXTURE_SIZE](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_atlases.cpp#L24) and [MIN_TEXTURE_SIZE](https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_atlases.cpp#L24) constants, which should result in fewer texture atlases.

Cheers,
Nils

**Comment by xueao** [comment]
@nmoehrle 
Hi Nils
Thank you for your advice.
I will try again.
Regards,
Xueao
