### ISSUE TITLE
Is MVE's PLY file the only input that dictates a textured model's color?

### ISSUE THREAD

**Issue by zharvey-welltok** [nmoehrle/mvs-texturing#60]
This is more of a conceptual question that I was hoping to get answered before I embark on it.

I have successfully ran a set of images through a fairly-long SfM pipeline involving OpenMVG, MVE and finally mvs-texturing. The result is a textured OBJ file that I can import into Blender and view. Very cool!

I would now like to manipulate that model programmatically by changing the RGB-color values for a subset of 3D points inside of it. The outcome would be that certain objects or sections inside the final textured model might appear, say, bright red, whereas they are *not* bright red in the original input images, etc.

I see that MVE's final output is a PLY file (`OUTPUT_MESH_CLEAN.ply`). I *believe* this is the main input for mvs-texturing, for example:

```
/path/to/texrecon MVE::undistorted MVE/OUTPUT_MESH_CLEAN.ply /path/to/output/mymodel
```

My *theory* is that I could:

1. Use a PLY reader (in a language of my choosing), combined with my own software to select the 3D points/vertices that I want to color/modify and set their new color values; then
2. Save the modified PLY file as, say, `OUT_MESH_CLEAN_MODIFIED.ply`; then
3. Load the modified PLY into mvs-texturing like I have already done with the non-modified one produced directly by MVE

Is this the correct course of action, or are there other inputs (for mvs-texturing) *besides* the PLY file that would also need to be changed in order to have the desired effect?

Thanks in advance!

**Comment by nmoehrle** [comment]
Hey there,

I am sorry but `texrecon` completely ignores the vertex colors of the input ply file. The textures are created solely from the given images.

Avoiding image warping is one of the core principles we employed in this work. This principle directly results in an implicit surface parameterization and therefore made it obsolete to implement an explicit mesh segmentation and parameterization. There is a basic mesh parameterization for small holes but it is based on mean value coordinates and unsuitable for larger segments. Therefore, it is not possible to ignore some faces during the texturing - they would not be included in final model due to the lack of a 2D parameterization.

However, you should be able to color certain faces in the final texture atlases. To implement this you would have to include face colors in the ply mesh and "render" those over the texture patches obtained during texturing. You would have to do this after the seam leveling and before the texture atlas generation ([texrecon.cpp:170](https://github.com/nmoehrle/mvs-texturing/blob/master/apps/texrecon/texrecon.cpp#L170)).

Best wishes

**Comment by zharvey-welltok** [comment]
OK thanks @nmoehrle I'll need a few days to digest this and give it a try. But I appreciate the feedback *enormously*!

**Comment by nmoehrle** [comment]
You're welcome :-)

On a second thought is there a reason why you want the intermediate ply file and not the obj file directly? `texrecon` uses only a small subset of the obj features and is therefore fairly easy to [parse](https://github.com/nmoehrle/mve/blob/master/libs/mve/mesh_io_obj.cc).

**Comment by zharvey-welltok** [comment]
No reason in particular, I'm just completely new to this and my above/proposed solution was the first thing I came up with!

Are you saying that it would be easier for me to parse the OBJ file and change its texture/colors directly?

**Comment by nmoehrle** [comment]
That depends on you scenario, but you could simply rasterize some faces into the texture atlas.
This mostly depends on how you determine which faces to color, but it might be easier that hacking the tex library.

**Comment by zharvey-welltok** [comment]
Ok, interesting! How about this:

1. Input image set; then
2. OpenMVG SfM pipeline (produces a sparse point cloud); then
3. MVE pipeline (produces a dense point cloud, represented by `OUTPUT_MESH_CLEAN.ply` PLY file); then
4. My custom software to read PLY file, obtain points/faces that I want to color, stores this info in a file somewhere (let's call it target-faces.json`); then
5. mvs-texturing (`texrecon`), produces the textured mesh (OBJ + MTL + various other files); then
6. My custom software to read both the OBJ file as well as `target-faces.json`, and essentially find the desired ('target') points/faces that we wish to color inside the OBJ file. Then it colors them.

Does this sound like an easier approach perhaps? If so, any suggestions on how I could accomplish Step 6 (actually coloring the points/faces ofthe OBJ file)? Thanks again!!

**Comment by nmoehrle** [comment]
One issue is that the face ids and potentially vertex ids change during step 5.

Therefore, it could become a little more difficult to identify the faces you saved before (especially since OBJ files contain the values in ascii which means that the vertices do not have the exact same coordinates and you would have to use an spatial acceleration structure to efficiently compute the correspondences - [libacc]( https://github.com/nmoehrle/libacc) could help ;-).

To avoid this you could combine step 4 and 6 - if your costum software can handle OBJ files.

Regarding step 6 once you know the correct face id's (which may include the OBJ part) you could calculate the aabb of the vertices uv coordinates, converting the uv coordinates to pixel coordinates and iterating over the aabb (in image space) coloring every pixel that is inside the triangle (of 2D uv coordinates). To determine whether a pixel is inside the triangle you can check if all barycentric coordinates are between 0 and 1, rasterization techniques based on the Bresenham algorithm are more efficient but usually result in more complex code.

**Comment by zharvey-welltok** [comment]
Thanks @nmoehrle but please remember I'm sadly a total newbie here; a few dummy questions should help me make sense of your last paragraph above:

* What is a "uv" coordinate, and how does it differ from a (2D?) pixel coordinate, and how does it differ from a 3D vertex/triangle coordinate?
* When you say "*...and iterating over the aabb (in image space) coloring every pixel...*" what are we actually iterating over? Pixel coordinates living inside the AABB? uv coordinates living inside the AABB? Something else?

Thanks!

**Comment by nmoehrle** [comment]
To texture a mesh (consisting of vertices and faces/triangles) with images one needs a 2D mapping of the meshes surface (the faces). The meshes surface is a 2D space inside the 3D space and a mapping is usually expressed as uv coordinates on the vertices of a face.

The simplest example is a single triangle in 3D.
To map the 3D surface to 2D we would assign the uv coordinates (0,0), (1,0) and (0,1) to the three vertices of the triangle (usually the is order is ccw).

By convention texture coordinates are in [0, 1] (lets ignore wrapping) and are interpolated with barycentric coordinates (fragment shaders automatically handle this). This means that you can now compute the uv coordinates for every point on the surface and given a images as texture you can also determine which pixels to display. The pixel coordinates are simply the uv coordinates multiplied by width and height (ignoring mip mapping - an anti-aliasing technique).

So to get to your question, a uv coordinate corresponds to an xy pixel coordinate in a texture atlas (fmod 1.0 and multiplied by the respective dimension).

To color this exemplary triangle you would calculate the AABB of the uv coordinates:
```min = (0,0), max = (1,1)``` 
and then iterate over the corresponding texture region:
```
for (int y = min[1]; y < max[1] * height; ++y)
    for (int x = min[0]; x < max[0] * width; ++x)
```
checking whether the pixel is inside the triangle e.g. using barycentric coordinates.

Sorry gotta go, hope that helps...

PS. Some file formats flip v (effectively 1.0 - v) this is due to the different coordinate system origins, top left (images) vs. bottom left (OpenGL))

**Comment by zharvey-welltok** [comment]
Thanks @nmoehrle I'll need some time to process all this, but I'll get back to you with my results! Thanks again for taking the time to help me here!

**Comment by nmoehrle** [comment]
Closing this - feel free to reopen if you have more questions.

**Comment by sucongCJS** [comment]
> Thanks @nmoehrle I'll need some time to process all this, but I'll get back to you with my results! Thanks again for taking the time to help me here!

have you got any result? 😃
