### ISSUE TITLE
tying cameras to mesh face

### ISSUE THREAD

**Issue by dakotabenjamin** [nmoehrle/mvs-texturing#75]
We received an interesting feature request over in OpenDroneMap: https://github.com/OpenDroneMap/OpenDroneMap/issues/557

The question is whether we can extract the camera information from each face?

**Comment by nmoehrle** [comment]
Sorry I somehow lost track of this issue.

There is currently no way to tell which cameras contributed to the reconstruction of a face (talking about geometry) if you use the MVE pipeline. The information gets lost once you export the depth maps into a pset (`scene2pset`).

If we talk about texture it becomes a little easier since we only use one image to texture a face you, for debug purposes you can visualize this mapping with the `--view_selection_model` as you probably know. The mapping gets lost once we combine texture patches to texture atlases. If you want to contain this information in a obj you would have to create one texture atlas per input image.
