### ISSUE TITLE
/tmp fills up causing libpng write error

### ISSUE THREAD

**Issue by dakotabenjamin** [nmoehrle/mvs-texturing#89]
When processing a large dataset, I will often set up a remote machine with a large mounted drive where the dataset is stored. `/` is only about 20GB. There are temporary files that are stored to `/tmp` so when it fills up the volume mvs-texturing will crash. Two questions:

1. Can these files be stored in a temporary folder local to the dataset?
2. Why are these temporary files so much bigger than the actual images? My images are 3-7MB but those in `/tmp` are 22-25MB. 

For reference I think the code in question is here: https://github.com/nmoehrle/mvs-texturing/blob/4fb24145a0201f7d18a1e3eb9ac2eecef624065c/libs/tex/generate_texture_views.cpp#L161

and https://github.com/nmoehrle/mvs-texturing/blob/master/libs/tex/generate_texture_views.cpp#L193

**Comment by bingzhang** [comment]
@dakotabenjamin, I found those files are open in memory and not closed. So in my code, I have to delete them to free memory and disk space as well.

**Comment by dakotabenjamin** [comment]
That would only work if it didn't run out of space. I'll post the error here: 
```
Load and prepare mesh:
PLY Loader: comment PCL generated
Reading PLY: 100675 verts... 199488 faces... done.
Warning: Zero-length normals detected: 4 face normals, 0 vertex normals
Generating texture views:
NVM: Loading file...
NVM: Number of views: 522
NVM: Number of features: 0
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
libpng error: Write Error
Aborted (core dumped)
Traceback (most recent call last):
  File "/mnt/volume-nyc3-02-part1/opendronemap/run.py", line 47, in <module>
    plasm.execute(niter=1)
  File "/mnt/volume-nyc3-02-part1/opendronemap/scripts/mvstex.py", line 124, in process
    '{keepUnseenFaces}'.format(**kwargs))
  File "/mnt/volume-nyc3-02-part1/opendronemap/opendm/system.py", line 34, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134
Traceback (most recent call last):
  File "run_dense.py", line 78, in <module>
    reconstructor(submodel_path)
  File "run_dense.py", line 55, in __call__
    '--start-with', 'opensfm'])
  File "run_dense.py", line 21, in run_command
    raise RuntimeError(result)
RuntimeError: 1
```

**Comment by dakotabenjamin** [comment]
Related, the images are being saved as jpg but are actually pngs

**Comment by nmoehrle** [comment]
Sadly this issue is a symptom of a larger problem, the nvm file support has not been implemented to the same standard as the MVE scene input format and this reveals itself in multiple points here.

With MVE scenes we require undistorted images and load those in only when needed to save memory. However, nvm files reference the original images. For the lazy loading to work we have to undistort the image and save them temporarily to disk. The choice of where was problematic here, but I think next to the other output files is a much better idea. Note that saving the images encoded as jpg would mean a loss in image quality (not only for images that have been provided in a lossless format). The last issue is that I did not maintain the information whether an image was a temporary, so I cannot delete them at the end.

To resolve a couple of this issues I propose that we save the image into a tmp folder within the output folder, replace the extension with '.png' and delete the tmp folder after successful completion.

Best,
Nils

**Comment by dakotabenjamin** [comment]
Nils,
Thanks for the thorough response. I have already partially completed some of the tasks you suggest. I'm relatively new at c++ so I hope it follows decent convention. I'll post the changes soon.

**Comment by nmoehrle** [comment]
Sorry I didn't see your response earlier I have implemented my proposed changes in #91 but I have not tested them yet.

**Comment by dakotabenjamin** [comment]
No worries, it looks better than mine. I can test with the nvm scene method.

**Comment by nmoehrle** [comment]
That would be awesome :-) Once I get your OK I'll merge into master.

**Comment by dakotabenjamin** [comment]
Thank you!
